spring.application.name=happyhomes
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5432/happyhome_db
spring.datasource.username=postgres
spring.datasource.password=system
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=86400000

cloudinary.cloud_name=dfc7ie2cd
cloudinary.api_key=822938386199899
cloudinary.api_secret=92z7uU6Zt3JpaVVj78wbiOwWjkY

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
